name: CI Pipeline

on: [push]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ vars.PYTHON_VERSION }}
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        uv sync --group dev
          
    - name: Unitary tests
      env:
        SRC_FOLDER: ${{ vars.SRC_FOLDER }}
        TESTS_UNIT_FOLDER: ${{ vars.TESTS_UNIT_FOLDER }}
        COV_PERCENT: ${{ vars.COV_PERCENT }}
      run: |
        uv run pytest --tb=short --cov=${SRC_FOLDER}/ ${TESTS_UNIT_FOLDER}/ --cov-fail-under=${COV_PERCENT} --cov-report=xml --cov-report=term-missing

    - name: Integration tests
      env:
        SRC_FOLDER: ${{ vars.SRC_FOLDER }}
        TESTS_INTEGRATION_FOLDER: ${{ vars.TESTS_INTEGRATION_FOLDER }}
        COV_PERCENT: ${{ vars.COV_PERCENT }}
      run: |
        uv run pytest --tb=short ${TESTS_INTEGRATION_FOLDER}
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: always()
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
