name: Pre CD Pipeline

on: 
  pull_request:
    branches:
      - main
      - staging

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ vars.PYTHON_VERSION }}
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        uv sync --group dev
          
    - name: Linter with pylint
      env:
        SRC_FOLDER: ${{ vars.SRC_FOLDER }}
        TEST_FOLDER: ${{ vars.TESTS_UNIT_FOLDER }}
        PYLINT_SCORE: ${{ vars.PYLINT_SCORE }}
      run: |
        uv run pylint ${SRC_FOLDER}/ ${TEST_FOLDER}/ --fail-under=${PYLINT_SCORE} --output-format=text > pylint_report.txt

    - name: Upload linter report
      uses: actions/upload-artifact@v3
      with:
        name: pylint-report
        path: pylint_report.txt
